### ISSUE TITLE
Instructions unclear a bit

### ISSUE THREAD

**Issue by two1212** [supsm/wp-florisboard#1]
Specifically, I don't understand the 4th step: "Zip contents"

If you can help me, it'll be great since I've been waiting for a keyboard (at least a skin) like this for a very long time. Thanks for making this!

**Comment by supsm** [comment]
Create a .zip file containing the contents of the repository. (The downloaded zip, if you did that, can't be used directly because it contains a sub-folder within the .zip)

Thanks for the issue report, I'll update the readme to hopefully make it more clear
